### PR TITLE
Feature shop

### PR DESCRIPTION
**Pull request by keltoff**
Added shops to game_logic. They contain either fixed cards or get drawn from a deck
Cost of the card is its inherent property, specified in json along with everything else.

Added event for buying cards. It would be handy to send a ref to the shop in the event, but lifetimes.

### CODE REVIEW

**Comment by Lycowolf** [comment]
I am trying to implement passing cards (and board state etc.) as references, and I am also hitting lifetime problems.

I don't want to merge more functionality that would be rewritten, so I am gonna delay merging this a few days (until I solve the problem or give up).

**Comment by Lycowolf** [comment]
I implemented a new stack machine prototype: the big change is that states can own previous states (making the stack implicit) and that state change is done directly by event() and update() methods, by returning the new state directly.

Please look at it in automaton_prototype and comment on it: if it looks OK to you, I can port the current version to it.

**Comment by keltoff** [comment]
I am a bit confused how exactly will the state changes work with more complicated call chains. It seems to me this is not a stack automaton but pure state switching, but that might not be a problem. I didn't look into the workings super well, though.
Except that, see no obvious problem with this. Having access to the parent state is obviously handy.

There is one problem with passing cards as references that is still in your prototype: we cannot distinguish identical cards from reference alone. I committed a demonstration in automaton_prototype. The code selects the third card from hand, but the first is played instead.
Worse yet, to match object instances to their reference would need directly comparing typecast pointers. 

What to do?
- compare pointers
- give cards IDs to make them unique
- live with it - identical cards are identical
- add additional info to event (card position in hand, frex.)
- something else?

**Comment by Lycowolf** [comment]
@keltoff are you gonna rebase this on master & resolve conflicts, or do you expect me to do it? I can, but this is your PR ;-)

Or is it obsolete?

**Comment by keltoff** [comment]
I'll do it. As you say, it's my part.

Dne út 11. 2. 2020 20:38 uživatel Lycowolf <notifications@github.com>
napsal:

**Comment by keltoff** [comment]
Shop functionality rebased and adapted to new Automaton model
+ Kaiju zone on the board, where kaiju go when drawn from the deck
+ Building zone on the board, where buildings can be played. You start with some.
+ Kaiju can raze buildings, but they don't do it yet
+ preparation for start_of_turn and end_of_turn actions

Prepared for **merge into the main branch**.

When these things are connected to UI, we will have a working rough skeleton of the game.

**Pull request merged**
